-- Optimization: usage metrics + KPI snapshots

create table if not exists public.usage_metrics (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  project_id uuid,
  analysis_run_id uuid references public.analysis_runs(id) on delete set null,
  request_id text,
  provider text,
  model text,
  prompt_tokens integer,
  completion_tokens integer,
  total_tokens integer,
  cost_usd numeric(10,4),
  latency_ms integer,
  cache_hit boolean default false,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists usage_metrics_occurred_at_idx on public.usage_metrics(occurred_at);
create index if not exists usage_metrics_project_idx on public.usage_metrics(project_id);
create index if not exists usage_metrics_run_idx on public.usage_metrics(analysis_run_id);

create table if not exists public.kpi_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null,
  project_id uuid,
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (snapshot_date, project_id)
);

create index if not exists kpi_snapshots_date_idx on public.kpi_snapshots(snapshot_date);
create index if not exists kpi_snapshots_project_idx on public.kpi_snapshots(project_id);
