-- Governance / Audit / Traceability core tables
create extension if not exists "pgcrypto";

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.analysis_runs (
  id uuid primary key default gen_random_uuid(),
  project_id uuid,
  asset_id uuid,
  status text not null default 'pending',
  progress smallint not null default 0,
  pipeline_version text,
  input_hash text,
  output_hash text,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint analysis_runs_progress_check check (progress >= 0 and progress <= 100)
);

drop trigger if exists set_analysis_runs_updated_at on public.analysis_runs;
create trigger set_analysis_runs_updated_at
before update on public.analysis_runs
for each row
execute function public.set_updated_at();

create table if not exists public.analysis_traceability (
  id uuid primary key default gen_random_uuid(),
  analysis_run_id uuid not null references public.analysis_runs(id) on delete cascade,
  insight_id uuid,
  export_id uuid,
  decision_fingerprint text,
  input_hash text,
  output_hash text,
  cache_key text,
  cache_hit boolean default false,
  latency_ms integer,
  token_cost_usd numeric(10,4),
  kpis jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists analysis_traceability_run_id_key on public.analysis_traceability(analysis_run_id);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_id uuid,
  actor_email text,
  actor_role text,
  action text not null,
  entity_type text not null,
  entity_id text,
  project_id uuid,
  analysis_run_id uuid,
  trace_id uuid,
  asset_id uuid,
  insight_id uuid,
  export_id uuid,
  request_id text,
  ip_address inet,
  user_agent text,
  input_hash text,
  output_hash text,
  diff jsonb,
  metadata jsonb not null default '{}'::jsonb,
  prev_hash text,
  hash text
);

create index if not exists audit_logs_action_idx on public.audit_logs(action);
create index if not exists audit_logs_entity_idx on public.audit_logs(entity_type, entity_id);
create index if not exists audit_logs_project_idx on public.audit_logs(project_id);
create index if not exists audit_logs_run_idx on public.audit_logs(analysis_run_id);
create index if not exists analysis_runs_project_idx on public.analysis_runs(project_id);
create index if not exists analysis_runs_asset_idx on public.analysis_runs(asset_id);
